/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dungeonadventuregui;


/**
 *
 * @author Jamie
 */
public class DungeonAdventureGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    
    DBManager database = new DBManager();
    
    public DungeonAdventureGUI() 
    {
        initComponents();
        ResizeImages resizeImg = new ResizeImages();
        Descriptions descriptionsText = new Descriptions();
        database.establishConnection();
        database.createTable();
        mainDungeonAdvImage.setIcon(resizeImg.resizeImage("D:\\Documents\\NetBeans -JAVA\\Projects\\Assignment 2-17981815\\Assignment2\\DungeonAdventureGUI\\src\\Images Used\\DungeonAdventure.jpg",mainDungeonAdvImage));
        this.introDescription.setText(descriptionsText.welcome());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        play = new javax.swing.JButton();
        showScoreboard = new javax.swing.JButton();
        quitMainWindow = new javax.swing.JButton();
        mainDungeonAdvImage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        introDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DungeonAdventure");

        play.setText("Play");
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });

        showScoreboard.setText("Scoreboard");
        showScoreboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showScoreboardActionPerformed(evt);
            }
        });

        quitMainWindow.setText("Quit");
        quitMainWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMainWindowActionPerformed(evt);
            }
        });

        mainDungeonAdvImage.setText("jLabel1");

        introDescription.setColumns(20);
        introDescription.setRows(5);
        jScrollPane2.setViewportView(introDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showScoreboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitMainWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(mainDungeonAdvImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainDungeonAdvImage, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(play)
                        .addGap(26, 26, 26)
                        .addComponent(showScoreboard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(quitMainWindow))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        dispose();
        CharacterSelection characterSelect = new CharacterSelection();
        characterSelect.setVisible(true);
        
    }//GEN-LAST:event_playActionPerformed

    private void quitMainWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMainWindowActionPerformed
        dispose();
    }//GEN-LAST:event_quitMainWindowActionPerformed

    private void showScoreboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showScoreboardActionPerformed
        int previousScore = database.getQuery();
        this.introDescription.setText(Integer.toString(previousScore));
        
    }//GEN-LAST:event_showScoreboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {

       // mainDungeonAdvImage.setIcon(resizeImg.resizeImage("\"D:\\\\Documents\\\\NetBeans -JAVA\\\\Projects\\\\Assignment 2-17981815\\\\Assignment2\\\\DungeonAdventureGUI\\\\src\\\\Images Used\\\\DungeonAdventure.jpg\"", mainDungeonAdvImage));
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DungeonAdventureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DungeonAdventureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DungeonAdventureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DungeonAdventureGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new DungeonAdventureGUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea introDescription;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mainDungeonAdvImage;
    private javax.swing.JButton play;
    private javax.swing.JButton quitMainWindow;
    private javax.swing.JButton showScoreboard;
    // End of variables declaration//GEN-END:variables
}
